contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://qcoding.net"
title: "Qi's Blog"
canonifyurls: true

params:
  logo: "/images/logo.jpg"
  github: "http://github.com/hongruiqi"
  copyright: "2016 Qi."
